### ISSUE TITLE
Passing relative url to svg icon as props 

### ISSUE THREAD

**Issue by BraydenGirard** [BraydenGirard/braydengirard#1]
Passing relative url to svg icon from Home.vue page as props to HeroCard.vue component is not working.

**Comment by alexmndzdev** [comment]
Hello, i've already the fix, but i can't do push.

**Comment by BraydenGirard** [comment]
You need to fork the repository, push the fix to your fork and then create a pull request.

**Comment by BraydenGirard** [comment]
Thanks a ton for the help Alex, glad you were able to get some experience with open source PR's. Keep up the good work!
